# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 659fa36805fcaff8bf7ff77c5033c17928c248250113a8eab3b875e00ae2ae148ee10a1281daa0ed277f68e3f04e63c2b87534c06fc2b9df8897f0b177c6005e

test:
  secret_key_base: b34438d4d3dbb4c5990ade5017b7b4057aa498dacd4b6b4d1a9d26e2e22b0896df73391fd3ab18634106a818300e2fae3bf3dcd58843b477166f726333391a6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
